/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Eduardo
 */
public class VentanaInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setVisible(true);
        pack();
        setLocationRelativeTo(null);
        //internalHome.setVisible(false);
        internalVehiculos.setVisible(false);
        internalModelos.setVisible(false);
        internalVentas.setVisible(false);
        internalProximamente.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBusqueda = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnModelos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnDocumentacion = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        internalHome = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        internalVehiculos = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaNumVehiculoBuscar = new javax.swing.JTextField();
        radioTipoBusqueda = new javax.swing.JRadioButton();
        radioModeloBusqueda = new javax.swing.JRadioButton();
        cajaNumSerieBuscar = new javax.swing.JTextField();
        comboModeloBusqueda = new javax.swing.JComboBox<>();
        radioNumSerieBusqueda = new javax.swing.JRadioButton();
        comboAnioBusqueda = new javax.swing.JComboBox<>();
        radioNumVehiculoBusqueda = new javax.swing.JRadioButton();
        comboTipoBusqueda = new javax.swing.JComboBox<>();
        radioAnioBusqueda = new javax.swing.JRadioButton();
        radioPrecioBusqueda1 = new javax.swing.JRadioButton();
        comboPrecioBusqueda1 = new javax.swing.JComboBox<>();
        internalModelos = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        internalVentas = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        internalProximamente = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autos Amistosos");
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(247, 227, 178));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\LOGO_chico.png")); // NOI18N
        sidePane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 140));

        btnCerrarSesion.setBackground(new java.awt.Color(227, 211, 163));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\cerrar_sesion.png")); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setToolTipText("");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        sidePane.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 220, 40));

        btnHome.setBackground(new java.awt.Color(214, 198, 152));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\home.png")); // NOI18N
        btnHome.setText("Home");
        btnHome.setToolTipText("");
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        sidePane.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 40));

        btnVehiculos.setBackground(new java.awt.Color(227, 211, 163));
        btnVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnVehiculos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\carro.png")); // NOI18N
        btnVehiculos.setText("Vehículos");
        btnVehiculos.setToolTipText("");
        btnVehiculos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        sidePane.add(btnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 40));

        btnModelos.setBackground(new java.awt.Color(227, 211, 163));
        btnModelos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModelos.setForeground(new java.awt.Color(0, 0, 0));
        btnModelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\modelo.png")); // NOI18N
        btnModelos.setText("Modelos");
        btnModelos.setToolTipText("");
        btnModelos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnModelos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelosActionPerformed(evt);
            }
        });
        sidePane.add(btnModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 40));

        btnVentas.setBackground(new java.awt.Color(227, 211, 163));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\ventas.png")); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setToolTipText("");
        btnVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        sidePane.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 40));

        btnEmpleados.setBackground(new java.awt.Color(227, 211, 163));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpleados.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\empleados.png")); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setToolTipText("");
        btnEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        sidePane.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 40));

        btnClientes.setBackground(new java.awt.Color(227, 211, 163));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnClientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\cliente.png")); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setToolTipText("");
        btnClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        sidePane.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, 40));

        btnDocumentacion.setBackground(new java.awt.Color(227, 211, 163));
        btnDocumentacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDocumentacion.setForeground(new java.awt.Color(0, 0, 0));
        btnDocumentacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\documento.png")); // NOI18N
        btnDocumentacion.setText("Docimentación");
        btnDocumentacion.setToolTipText("");
        btnDocumentacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDocumentacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentacionActionPerformed(evt);
            }
        });
        sidePane.add(btnDocumentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, 40));

        bg.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 221, 615));

        internalHome.setBackground(new java.awt.Color(255, 255, 255));
        internalHome.setTitle("Home");
        internalHome.setToolTipText("");
        internalHome.setVisible(false);
        internalHome.getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hola Bienvenido a Autos Amistosos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 443, 66);

        internalHome.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 570);

        jDesktopPane1.add(internalHome);
        internalHome.setBounds(0, 0, 770, 610);

        internalVehiculos.setTitle("Vehiculos");
        internalVehiculos.setVisible(true);
        internalVehiculos.getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(214, 198, 152));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Vehículos");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\ITSJ\\5. Quinto Semestre\\Taller de bases de datos\\Proyecto final\\Proyecto_Final_TBD_Escritorio\\src\\main\\java\\img\\logo_oscuro.png")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 548, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 0, 760, 60);

        cajaNumVehiculoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumVehiculoBuscar.setText("Buscar");
        cajaNumVehiculoBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cajaNumVehiculoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNumVehiculoBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(cajaNumVehiculoBuscar);
        cajaNumVehiculoBuscar.setBounds(30, 100, 210, 30);

        groupBusqueda.add(radioTipoBusqueda);
        radioTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioTipoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioTipoBusqueda.setText("Tipo");
        jPanel2.add(radioTipoBusqueda);
        radioTipoBusqueda.setBounds(510, 150, 200, 25);

        groupBusqueda.add(radioModeloBusqueda);
        radioModeloBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioModeloBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioModeloBusqueda.setText("Modelo");
        radioModeloBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModeloBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(radioModeloBusqueda);
        radioModeloBusqueda.setBounds(510, 70, 170, 25);

        cajaNumSerieBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumSerieBuscar.setText("Buscar");
        cajaNumSerieBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cajaNumSerieBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNumSerieBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(cajaNumSerieBuscar);
        cajaNumSerieBuscar.setBounds(270, 100, 210, 30);

        comboModeloBusqueda.setBackground(new java.awt.Color(214, 198, 152));
        comboModeloBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        comboModeloBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboModeloBusqueda);
        comboModeloBusqueda.setBounds(510, 100, 210, 26);

        groupBusqueda.add(radioNumSerieBusqueda);
        radioNumSerieBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioNumSerieBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioNumSerieBusqueda.setText("Número de Serie");
        radioNumSerieBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNumSerieBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(radioNumSerieBusqueda);
        radioNumSerieBusqueda.setBounds(260, 70, 170, 25);

        comboAnioBusqueda.setBackground(new java.awt.Color(214, 198, 152));
        comboAnioBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        comboAnioBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboAnioBusqueda);
        comboAnioBusqueda.setBounds(30, 180, 210, 26);

        groupBusqueda.add(radioNumVehiculoBusqueda);
        radioNumVehiculoBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioNumVehiculoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioNumVehiculoBusqueda.setText("Número de Vehículo");
        jPanel2.add(radioNumVehiculoBusqueda);
        radioNumVehiculoBusqueda.setBounds(30, 70, 170, 25);

        comboTipoBusqueda.setBackground(new java.awt.Color(214, 198, 152));
        comboTipoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        comboTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboTipoBusqueda);
        comboTipoBusqueda.setBounds(510, 180, 210, 26);

        groupBusqueda.add(radioAnioBusqueda);
        radioAnioBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioAnioBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        radioAnioBusqueda.setText("Año de Fabricación");
        jPanel2.add(radioAnioBusqueda);
        radioAnioBusqueda.setBounds(30, 150, 200, 25);

        groupBusqueda.add(radioPrecioBusqueda1);
        radioPrecioBusqueda1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioPrecioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        radioPrecioBusqueda1.setText("Precio Menor A:");
        jPanel2.add(radioPrecioBusqueda1);
        radioPrecioBusqueda1.setBounds(270, 150, 200, 25);

        comboPrecioBusqueda1.setBackground(new java.awt.Color(214, 198, 152));
        comboPrecioBusqueda1.setForeground(new java.awt.Color(0, 0, 0));
        comboPrecioBusqueda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboPrecioBusqueda1);
        comboPrecioBusqueda1.setBounds(270, 180, 210, 26);

        internalVehiculos.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalVehiculos);
        internalVehiculos.setBounds(0, 0, 770, 610);

        internalModelos.setTitle("Modelos");
        internalModelos.setVisible(false);
        internalModelos.getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Modelos");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 40, 420, 90);

        internalModelos.getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalModelos);
        internalModelos.setBounds(0, 0, 770, 610);

        internalVentas.setTitle("Ventas");
        internalVentas.setVisible(false);
        internalVentas.getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ventas");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 10, 140, 40);

        internalVentas.getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalVentas);
        internalVentas.setBounds(0, 0, 770, 620);

        internalProximamente.setTitle("Proximamente");
        internalProximamente.setVisible(false);
        internalProximamente.getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estamos trabajando en la construcción de esta página");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(60, 50, 640, 80);

        internalProximamente.getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 760, 580);

        jDesktopPane1.add(internalProximamente);
        internalProximamente.setBounds(0, 0, 770, 610);

        bg.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 770, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ocultarInternal(JInternalFrame internalVisible, JInternalFrame... internals){
        
        for(JInternalFrame i : internals){
            
            i.setVisible(false);
            
        }
        
        internalVisible.setVisible(true);
        
    }
    
    private void cambiarColorBoton(JButton... btnMenu){
        
        for(JButton i : btnMenu){
            
            i.setBackground(new java.awt.Color(227,211,163));
            
        }
        
    }
    
    
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {

                new VentanaLogin();

            }
        });
        
        setVisible(false);
        
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
        // Cambio de Colores de Botones
        
        cambiarColorBoton(btnCerrarSesion, btnVehiculos, btnModelos, btnVentas, btnEmpleados, btnClientes, btnDocumentacion);
        
        btnHome.setBackground(new java.awt.Color(214,198,152));
        
        // Abrir Frame
        
        ocultarInternal(internalHome, internalVehiculos, internalModelos);
        
        
        
       
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        
        cambiarColorBoton(btnCerrarSesion, btnHome, btnModelos, btnVentas, btnEmpleados, btnClientes, btnDocumentacion);
        
        btnVehiculos.setBackground(new java.awt.Color(214,198,152));
        
        ocultarInternal(internalVehiculos, internalHome, internalModelos);
        
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelosActionPerformed
        
        cambiarColorBoton(btnCerrarSesion, btnHome, btnVehiculos, btnVentas, btnEmpleados, btnClientes, btnDocumentacion);
        
        btnModelos.setBackground(new java.awt.Color(214,198,152));
        
        ocultarInternal(internalModelos, internalHome, internalVehiculos);
        
    }//GEN-LAST:event_btnModelosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        
        cambiarColorBoton(btnCerrarSesion, btnHome, btnModelos, btnVehiculos, btnEmpleados, btnClientes, btnDocumentacion);
        
        btnVentas.setBackground(new java.awt.Color(214,198,152));
        
        ocultarInternal(internalVentas, internalHome, internalModelos, internalVehiculos);
        
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        
        cambiarColorBoton(btnCerrarSesion, btnHome, btnModelos, btnVentas, btnVehiculos, btnClientes, btnDocumentacion);
        
        btnEmpleados.setBackground(new java.awt.Color(214,198,152));
        
        ocultarInternal(internalProximamente, internalHome, internalModelos, internalVehiculos, internalVentas);
        
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        
        cambiarColorBoton(btnCerrarSesion, btnHome, btnModelos, btnVentas, btnEmpleados, btnVehiculos, btnDocumentacion);
        
        btnClientes.setBackground(new java.awt.Color(214,198,152));
        
        ocultarInternal(internalProximamente, internalHome, internalModelos, internalVehiculos, internalVentas);
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentacionActionPerformed
        
        cambiarColorBoton(btnCerrarSesion, btnHome, btnModelos, btnVentas, btnEmpleados, btnClientes, btnVehiculos);
        
        btnDocumentacion.setBackground(new java.awt.Color(214,198,152));
        
        ocultarInternal(internalProximamente, internalHome, internalModelos, internalVehiculos, internalVentas);
        
    }//GEN-LAST:event_btnDocumentacionActionPerformed

    private void cajaNumVehiculoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNumVehiculoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNumVehiculoBuscarActionPerformed

    private void cajaNumSerieBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNumSerieBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNumSerieBuscarActionPerformed

    private void radioModeloBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModeloBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioModeloBusquedaActionPerformed

    private void radioNumSerieBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNumSerieBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNumSerieBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDocumentacion;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnModelos;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JButton btnVentas;
    private javax.swing.JTextField cajaNumSerieBuscar;
    private javax.swing.JTextField cajaNumVehiculoBuscar;
    private javax.swing.JComboBox<String> comboAnioBusqueda;
    private javax.swing.JComboBox<String> comboModeloBusqueda;
    private javax.swing.JComboBox<String> comboPrecioBusqueda1;
    private javax.swing.JComboBox<String> comboTipoBusqueda;
    private javax.swing.ButtonGroup groupBusqueda;
    private javax.swing.JInternalFrame internalHome;
    private javax.swing.JInternalFrame internalModelos;
    private javax.swing.JInternalFrame internalProximamente;
    private javax.swing.JInternalFrame internalVehiculos;
    private javax.swing.JInternalFrame internalVentas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton radioAnioBusqueda;
    private javax.swing.JRadioButton radioModeloBusqueda;
    private javax.swing.JRadioButton radioNumSerieBusqueda;
    private javax.swing.JRadioButton radioNumVehiculoBusqueda;
    private javax.swing.JRadioButton radioPrecioBusqueda1;
    private javax.swing.JRadioButton radioTipoBusqueda;
    private javax.swing.JPanel sidePane;
    // End of variables declaration//GEN-END:variables
}
